language: node_js
node_js:
  - "stable"
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/lcov.info
  - ./cc-test-reporter upload-coverage
script:
  - npm run test
notifications:
  - email:
    - development@barterout.com